"""Helpers for resolving project directories from seed and runtime context."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import structlog

log = structlog.get_logger(__name__)


def resolve_path_against_base(
    raw_path: str | Path | None,
    *,
    stable_base: Path,
    enforce_containment: bool = False,
) -> Path | None:
    """Resolve a path against a stable base directory.

    When ``enforce_containment`` is True the resolved path (after tilde
    expansion and symlink resolution) must live inside ``stable_base``;
    otherwise ``None`` is returned and a containment-violation warning is
    logged. Callers handling untrusted input (e.g. seed-encoded paths) must
    opt in so absolute paths and ``..`` traversal cannot escape the
    project directory.
    """
    if raw_path is None:
        return None

    candidate = Path(raw_path).expanduser()
    if candidate.is_absolute():
        resolved = candidate.resolve()
    else:
        resolved = (stable_base / candidate).resolve()

    if enforce_containment:
        base_resolved = stable_base.resolve()
        if resolved != base_resolved:
            try:
                resolved.relative_to(base_resolved)
            except ValueError:
                log.warning(
                    "project_paths.containment_violation",
                    raw_path=str(raw_path),
                    resolved=str(resolved),
                    stable_base=str(base_resolved),
                )
                return None

    return resolved


def project_path_candidates_from_seed(seed: Any) -> tuple[str, ...]:
    """Extract likely project directories from seed metadata and brownfield refs."""
    if seed is None:
        return ()

    candidates: list[str] = []
    seed_meta = getattr(seed, "metadata", None)
    if seed_meta is not None:
        project_dir = getattr(seed_meta, "project_dir", None) or getattr(
            seed_meta,
            "working_directory",
            None,
        )
        if isinstance(project_dir, str) and project_dir:
            candidates.append(project_dir)

    brownfield_context = getattr(seed, "brownfield_context", None)
    context_references = getattr(brownfield_context, "context_references", ()) or ()

    for reference in context_references:
        path = getattr(reference, "path", None)
        role = getattr(reference, "role", None)
        if isinstance(path, str) and path and role == "primary" and path not in candidates:
            candidates.append(path)

    for reference in context_references:
        path = getattr(reference, "path", None)
        if isinstance(path, str) and path and path not in candidates:
            candidates.append(path)

    return tuple(candidates)


def resolve_seed_project_path(seed: Any, *, stable_base: Path) -> Path | None:
    """Resolve the highest-priority project path encoded in a seed.

    Seed-encoded paths originate from untrusted sources — seeds may be
    imported via ``ooo publish`` or generated by an LLM — so every candidate
    is required to resolve inside ``stable_base``. Candidates are tried in
    priority order (metadata first, then primary brownfield references,
    then remaining references); each escaping candidate is rejected with a
    containment-violation log entry, and the next candidate is evaluated.
    The function returns ``None`` when no candidate is contained — every
    returned path is therefore inside ``stable_base``.
    """
    for candidate in project_path_candidates_from_seed(seed):
        resolved = resolve_path_against_base(
            candidate,
            stable_base=stable_base,
            enforce_containment=True,
        )
        if resolved is not None:
            return resolved
    return None
